/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/model.glb -o public/models/Model.jsx --transform 
Files: public/models/model.glb [7.57MB] > C:\3D-project\public\models\model-transformed.glb [320.24KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.TexMap} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
