/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.TexMap} />
      <mesh geometry={nodes.mesh_1.geometry} material={materials.TexMap} />
      <mesh geometry={nodes.mesh_2.geometry} material={materials.TexMap} />
      <mesh geometry={nodes.mesh_3.geometry} material={materials.TexMap} />
    </group>
  )
}

useGLTF.preload('/model.glb')
